# Generated by Django 2.1.7 on 2019-02-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=100)),
                ('total_seat', models.CharField(max_length=2)),
            ],
        ),
    ]
