# Generated by Django 2.1.7 on 2019-02-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_status', models.CharField(choices=[('OT', 'On Travel'), ('IS', 'In Service'), ('AB', 'Booked')], max_length=2)),
                ('car_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_cars.Car')),
            ],
        ),
    ]
