# Generated by Django 2.1.7 on 2019-02-27 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_cars', '0005_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_to', models.CharField(max_length=20)),
                ('journey_date', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_cars.Car')),
                ('custoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_cars.Customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_cars.Driver')),
                ('journey_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_cars.Location')),
            ],
        ),
        migrations.AlterField(
            model_name='carstatus',
            name='car_status',
            field=models.CharField(choices=[('AV', 'Available'), ('OT', 'On Travel'), ('IS', 'In Service'), ('AB', 'Booked')], max_length=2),
        ),
    ]
