# Generated by Django 2.1.7 on 2019-02-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_cars', '0006_auto_20190227_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentcar',
            old_name='custoner',
            new_name='customer',
        ),
    ]
